<a href="https://colab.research.google.com/github/hafizdabo/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week1solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arewa Data Science Academy
## Deep Learning Cohort2.0
### Name: Abdulhafiz Umar Dabo
### Email: hafizdabo@gmail.com
### Title: Week 1 Solution
### Exercises Solution

### Creating a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor with shape (7, 7)
random_tensor = torch.rand(7, 7)

# Printing the tensor
print(random_tensor)

tensor([[5.5691e-02, 3.5993e-02, 6.6222e-01, 5.2236e-01, 2.4272e-01, 3.6640e-01,
         2.7173e-01],
        [6.9580e-02, 5.5019e-02, 8.7779e-02, 1.7246e-01, 9.7185e-01, 2.8156e-01,
         3.8297e-01],
        [5.3671e-02, 7.5956e-01, 5.6361e-01, 6.6922e-01, 3.2051e-01, 7.1685e-01,
         3.8781e-01],
        [3.8975e-01, 9.6073e-01, 1.9201e-01, 2.6687e-01, 6.9570e-01, 9.5716e-01,
         8.9069e-01],
        [2.8044e-01, 9.5867e-01, 8.1983e-01, 3.7544e-02, 3.6970e-01, 7.9320e-02,
         3.9507e-01],
        [7.8330e-01, 5.3403e-01, 1.0347e-04, 9.4199e-01, 8.6532e-01, 5.1932e-02,
         3.8435e-01],
        [2.3432e-01, 9.8415e-01, 6.3488e-01, 5.5409e-01, 3.8890e-01, 9.2357e-01,
         6.9032e-01]])


### 3. Performing a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)`

In [ ]:
# Create another random tensor
random_tensor2 = torch.rand(1, 7)

# Performing matrix multiplication
result = torch.matmul(random_tensor, random_tensor2.T)

# Printing the result
print(result)


tensor([[1.4295],
        [0.9624],
        [2.1375],
        [2.3611],
        [1.6209],
        [1.7746],
        [2.6311]])


### 4. Setting the random seed to `0` and do 2 & 3 over again.

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors with shapes (7, 7) and (1, 7)
rand_tensor = torch.rand(7, 7)
rand_tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
result2 = torch.matmul(rand_tensor, rand_tensor2.T)

# Printing the result
print(result2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    # Send the tensors to the GPU
    device = torch.device("cuda")  # If GPU is available, use it
else:
    # Fallback to CPU if no GPU is available
    device = torch.device("cpu")

# Create two random tensors on GPU
tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)

# Print the tensors and their device location
print("Tensor 1:", tensor1)
print("Tensor 2:", tensor2)
print("Device:", device)

Tensor 1: tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
Tensor 2: tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')
Device: cuda



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor1 and tensor2, and transpose tensor2 to shape (3, 2).
result3 = torch.matmul(tensor1, tensor2.T)

# Print the result and its shape
print("Matrix multiplication result:\n", result3)
print("Result shape:", result3.shape)

Matrix multiplication result:
 tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')
Result shape: torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_value = torch.max(result3)

# Find min
min_value = torch.min(result3)

# Print the maximum and minimum values
print("Maximum value in the result:", max_value)
print("Minimum value in the result:", min_value)

Maximum value in the result: tensor(0.7668, device='cuda:0')
Minimum value in the result: tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
arg_max = torch.argmax(result3)

# Find arg min
arg_min = torch.argmin(result3)

# Print the indices of the maximum and minimum values
print("Index of the maximum value in the result:", arg_max)
print("Index of the minimum value in the result:", arg_min)

Index of the maximum value in the result: tensor(1, device='cuda:0')
Index of the minimum value in the result: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensorr = torch.rand(1, 1, 1, 10)

# Remove single dimensions
new_tensor = random_tensorr.squeeze()

# Print out the original tensor and its shape
print("Original tensor:")
print(random_tensorr)
print("Original tensor shape:", random_tensorr.shape)

# Print out the new tensor and its shape
print("\nNew tensor:")
print(new_tensor)
print("New tensor shape:", new_tensor.shape)


Original tensor:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Original tensor shape: torch.Size([1, 1, 1, 10])

New tensor:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
New tensor shape: torch.Size([10])
